name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl binutils

      - name: Process
        run: |
          chmod +x lib/arm64-v8a/*.so lib/armeabi-v7a/*.so
          for f in lib/arm64-v8a/*.so lib/armeabi-v7a/*.so; do
            strip --strip-all --remove-section=.comment --remove-section=.note "$f"
            upx --best --ultra-brute "$f" || true
          done

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Optimize binaries"
          branch: main
